import { Inter } from "next/font/google";
import SideNavbar from "@/app/ui/Jobs/Sidebar/Sidebar";
import BottomNavigation from "@/app/ui/Jobs/BottomNavigation/BottomNavigation";
import TopBar from "@/app/ui/Jobs/Topbar/TopBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='selection:bg-lime'>
                    <SideNavbar />
                </div>
                <div className="lg:ml-72 selection:bg-lime ">
                    <TopBar />
                    {children}
                </div>
                <BottomNavigation />
            </body>
        </html>
    );
}
